#! /bin/csh -f

# get level 2 data from AWS

mkdir -p /scr/cirrus1/rsfdata/projects/nexrad/level2
cd /scr/cirrus1/rsfdata/projects/nexrad/level2

GetAwsRadar.py --radarName KOUN --outputDir . --start "2011 04 15 01 00 00" --end "2011 04 15 02 00 00" --debug
GetAwsRadar.py --radarName KOUN --outputDir . --start "2011 04 08 13 00 00" --end "2011 04 08 14 00 00" --debug
GetAwsRadar.py --radarName KOUN --outputDir . --start "2011 05 24 21 00 00" --end "2011 05 24 22 00 00" --debug
GetAwsRadar.py --radarName KOUN --outputDir . --start "2010 04 17 18 00 00" --end "2010 04 17 19 00 00" --debug
GetAwsRadar.py --radarName KRIW --outputDir . --start "2017 01 24 16 00 00" --end "2017 01 24 17 00 00" --debug
GetAwsRadar.py --radarName KBUF --outputDir . --start "2022 11 18 08 00 00" --end "2022 11 18 09 00 00" --debug
GetAwsRadar.py --radarName NOP4 --outputDir . --start "2013 05 20 20 00 00" --end "2013 05 20 21 00 00" --debug
GetAwsRadar.py --radarName KIWA --outputDir . --start "2011 05 31 11 00 00" --end "2011 05 31 12 00 00" --debug
GetAwsRadar.py --radarName KMHX --outputDir . --start "2011 06 26 09 30 00" --end "2011 06 26 10 30 00" --debug
GetAwsRadar.py --radarName KTBW --outputDir . --start "2022 09 28 15 30 00" --end "2022 09 28 16 30 00" --debug
