#! /bin/csh -f

# Back up MPD data in mpd_##_data folder

set DATA_DIR="/scr/cirrus2/rsfdata/projects/nexrad-mrms/MergedDbzQC"

set YEAR="2021"
set MONTH="05"

#set DIRS=(${YEAR}${MONTH}01 ${YEAR}${MONTH}02 ${YEAR}${MONTH}03 ${YEAR}${MONTH}04 ${YEAR}${MONTH}05 ${YEAR}${MONTH}06 ${YEAR}${MONTH}07 ${YEAR}${MONTH}08 ${YEAR}${MONTH}09 ${YEAR}${MONTH}10 ${YEAR}${MONTH}11 ${YEAR}${MONTH}12 ${YEAR}${MONTH}13 ${YEAR}${MONTH}14 ${YEAR}${MONTH}15 ${YEAR}${MONTH}16 ${YEAR}${MONTH}17 ${YEAR}${MONTH}18 ${YEAR}${MONTH}19 ${YEAR}${MONTH}20 ${YEAR}${MONTH}21 ${YEAR}${MONTH}22 ${YEAR}${MONTH}23 ${YEAR}${MONTH}24 ${YEAR}${MONTH}25 ${YEAR}${MONTH}26 ${YEAR}${MONTH}27 ${YEAR}${MONTH}28 ${YEAR}${MONTH}29 ${YEAR}${MONTH}30 ${YEAR}${MONTH}31)

set DIRS=(${YEAR}${MONTH}01 ${YEAR}${MONTH}02 ${YEAR}${MONTH}03 ${YEAR}${MONTH}04 ${YEAR}${MONTH}05 ${YEAR}${MONTH}06 ${YEAR}${MONTH}07 ${YEAR}${MONTH}08 ${YEAR}${MONTH}09 ${YEAR}${MONTH}10 ${YEAR}${MONTH}11 ${YEAR}${MONTH}12 ${YEAR}${MONTH}13)

set LEVS=(00.50 00.75 01.00 01.25 01.50 01.75 02.00 02.25 02.50 02.75 03.00 03.50 04.00 04.50 05.00 05.50 06.00 06.50 07.00 07.50 08.00 08.50 09.00 10.00 11.00 12.00 13.00 14.00 15.00 16.00 17.00 18.00 19.00)

cd $DATA_DIR

foreach i ( $DIRS )
set DATE=$i
echo $DATE

cd $DATE

foreach k ( $LEVS )
set AWSNUM=`aws s3 ls --no-sign-request s3://noaa-mrms-pds/CONUS/MergedReflectivityQC_$k/$DATE --recursive | wc -l`
set LOCNUM=`ls -1 MergedReflectivityQC_{$k}_* | wc -l`
@ AMINL=( $AWSNUM - $LOCNUM )
if ( $AMINL  != 0 ) then
echo $DATE $k - AWS minus LOCAL = $AMINL
endif
end

cd $DATA_DIR
end
