#! /bin/csh -f

# Back up MPD data in mpd_##_data folder

set DATA_DIR="/scr/cirrus2/rsfdata/projects/nexrad-mrms/MergedDbzQC"

#set YEAR="2022"
#set MONTH="03"

set YEAR=$1
set MONTH=$2
set DAY=$3

set DIRS=(${YEAR}${MONTH}${DAY})

set LEVS=(00.50 00.75 01.00 01.25 01.50 01.75 02.00 02.25 02.50 02.75 03.00 03.50 04.00 04.50 05.00 05.50 06.00 06.50 07.00 07.50 08.00 08.50 09.00 10.00 11.00 12.00 13.00 14.00 15.00 16.00 17.00 18.00 19.00)

cd $DATA_DIR

foreach i ( $DIRS )
set DATE=$i
echo $DATE

cd $DATE

foreach k ( $LEVS )
set AWSNUM=`aws s3 ls --no-sign-request s3://noaa-mrms-pds/CONUS/MergedReflectivityQC_$k/$DATE --recursive | wc -l`
set LOCNUM=`ls -1 MergedReflectivityQC_{$k}_* | wc -l`
@ AMINL=( $AWSNUM - $LOCNUM )
if ( $AMINL  != 0 ) then
echo $DATE $k - AWS minus LOCAL = $AMINL
endif
end

cd $DATA_DIR
end
